# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Jar an Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/VaillantMqttClient-jar-with-dependencies.jar staging
      - run: mv staging/VaillantMqttClient-jar-with-dependencies.jar staging/VaillantMqttClient.jar
      - uses: actions/upload-artifact@v3
        with:
          name: VaillantMqttClient-Jar
          path: staging

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: VaillantMqttClient-Jar
          path: target/
      - name: Docker build
        run: |
          docker build . -t vaillant_mqtt_client --platform linux/amd64,linux/arm64,linux/arm/v7
      - run: docker save -o target/VaillantMqttClient.tar vaillant_mqtt_client:latest
      - run: mkdir staging && cp target/*.tar staging
      - uses: actions/upload-artifact@v3
        with:
          name: VaillantMqttClient-Docker
          path: staging